
module.exports = {
  SERVER_ERROR                : 'something went wrong',
  DATABASE_QUERY_ERROR        : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE : 'Error in Connecting with Database',
  GET_RECORD                  : 'Record(s) fetched successfully',
  DATA_NOT_FOUND              : 'No matching record found',
  PARAMETER_MISSING           : 'Id parameter missing',
  INVALID_PARAMETER           : 'Invalid parameter',
  GET_FAILURE                 : 'record get failed',
  DELETE_CACHE                : 'cache deleted',
  ADD_SUCCESS                 : 'Task created successfully',
  ADD_FAILURE                 : 'Task add failed',
  UPDATE_SUCCESS              : 'Task updated successfully',
  UPDATE_FAILURE              : 'Task update failed',
  AUTH_TOKEN_MISSING          : 'authorization header is missing',
  API_TOKEN_MISSING           : 'Please enter API key or token.',
  INVALID_API_TOKEN           : 'Please enter valid API Key or token.',
  PERMISSION_REQUIRED         : 'You do not have required permission to try this API.',
  INVALID_AUTH_TOKEN          : 'invalid authorization header',
  INVALID_TOKEN               : 'invalid token',
  SOMETHING_WENT_WRONG        : 'something went wrong, task not added',
  NO_TASK_IMAGE               : 'No images uploaded',
  NO_TASK_ASSIGNED            : 'No Tasks Assigned',
  GET_DATA_FAILED             : 'Not able to fetch Record. Something went wrong',
  DELETE_SUCCESS              : 'Task deleted successfully',
  DELETE_FAIL                 : 'Something went wrong, you can not delete this task',
  DELETE_INCOMPLETE           : 'One or more assignees have completed this task, so the task cannot be deleted',
  TASK_COMPLETED              : 'Task completed successfully',
  SKILL_REASSESSED_COMPLETED  : 'Skill Reassessed Successfully',
  TASK_UPDATE_FAILED          : 'Task update failed',
  NOT_ALLOWED_PERMISSION      : 'You have not permission for this action',
  ROLE_PERMISSION_REQUIRED    : 'Valid Role and Permission Required',
  INVALID_EMPLOYEE            : 'You no longer have access to your company\'s OneTeam360 workspace. Please contact your administrator if you believe this is a mistake',
  HEALTH_OK                   : 'Health check passed',
  TASK_IMAGE_NOT_SELECTED     : 'Please select an image to upload',
  INVALID_TASK_IMAGE_TYPE     : 'Invalid file type, allowed file types: jpg, png, jpeg',
  TASK_IMAGE_UPLOAD_SUCCESS   : 'Task image uploaded successfully',
  TASK_IMAGE_UPLOAD_FAILURE   : 'Task image upload failed',
  FILE_SIZE_LIMIT_EXCEEDED    : 'maximum file size exceeded, max allowed size is STR_TO_BE_REPLACEMB',
  MAX_FILE_UPLOAD_ERR_MSG     : 'Maximum number of files exceeded, limit is STR_TO_BE_REPLACE at most',
  MAX_FILE_LIMIT_EXCEEDED     : 'You cannot upload more than 5 images',
};
