
module.exports = {
  REGISTER_SUCCESS                 : 'Team member account created successfully. A welcome email will be sent on registered email address shortly.',
  REGISTER_FAILURE                 : 'signup request failed',
  USER_ALREADY_EXISTS              : 'User with this email is already exists',
  USER_NOT_FOUND                   : 'user with this email doesn\'t exist',
  PERMISSION_DENIED_DOH            : 'Permission denied to update date of Hire ',
  PERMISSION_DENIED_EMAIL          : 'Permission denied to update team member email id',
  INCORRECT_CREDENTIALS            : 'incorrect username or password',
  LOGIN_SUCCESS                    : 'successfully login',
  LOGIN_FAILURE                    : 'login request failed',
  SERVER_ERROR                     : 'something went wrong',
  RECORD_EXIST                     : 'Record Already Exist',
  DATABASE_QUERY_ERROR             : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE      : 'Error in Connecting with Database',
  ADMIN_ACCESS_REQUIRED            : 'Valid access required',
  AUTH_TOKEN_MISSING               : 'authorization header is missing',
  API_TOKEN_MISSING                : 'Please enter API key or token.',
  INVALID_API_TOKEN                : 'Please enter valid API Key or token.',
  INVALID_AUTH_TOKEN               : 'invalid authorization header',
  INVALID_TOKEN                    : 'invalid token',
  INVALID_EMPLOYEE                 : 'You no longer have access to your company\'s OneTeam360 workspace. Please contact your administrator if you believe this is a mistake',
  GET_RECORD                       : 'Record(s) fetched successfully',
  GET_RECORD_FAILURE               : 'Not able to fetch Record. Something went wrong',
  ADD_SUCCESS                      : 'Record add successful',
  ADD_FAILURE                      : 'Record add failed',
  UPDATE_SUCCESS                   : 'Team member profile updated successfully',
  UPDATE_FAILURE                   : 'Record update failed',
  DELETE_RECORD                    : 'Record successfully deleted',
  DELETE_FAILURE                   : 'Record Delete Failure',
  SUCCESS_UPLOAD                   : 'Document Uploaded Successfully',
  DATA_NOT_FOUND                   : 'No matching record found',
  ALLOWED_IMAGES                   : ['image/jpeg', 'image/png'],
  INVALID_FILE_TYPE                : 'invalid file type, only png/jpeg files are allowed',
  FILE_SIZE_LIMIT_EXCEEDED         : 'maximum file size exceeded, max allowed size is STR_TO_BE_REPLACEMB',
  EMPLOYEE_LOCATIONS               : 'Team member Location List',
  NOTE_TYPES                       : 'Note Types List',
  ADD_NOTE_SUCCESS                 : 'Note added successfully.',
  ADD_NOTE_FAILURE                 : 'Note add failure',
  NO_NOTES_ADDED                   : 'No Notes Added',
  NOTE_TYPE_NOT_EXIST              : 'Note type not exist in our system',
  NOTE_DELETE_SUCCESS              : 'Note removed successfully.',
  PARAMETER_MISSING                : 'Parameter missing',
  CERTIFICATE_TYPES                : 'Certificate Types',
  ASSIGN_CERTIFICATE_FAILURE       : 'Certificate assigned failure.',
  ASSIGN_CERTIFICATE_TASK_FAILURE  : 'Certificate assigned task failure.',
  ASSIGN_CERTIFICATE               : 'Certificate assigned successfully.',
  ADD_CERTIFICATE_FAILURE          : 'Certificate add failure.',
  CERTIFICATE_ALREADY_ADDED        : 'The certificate is already assigned to the team member.',
  ADD_CERTIFICATE_TASK_FAILURE     : 'Certificate add task failure.',
  ADD_CERTIFICATE                  : 'Certificate added successfully.',
  NO_CERTIFICATE_ADDED             : 'No Certificates Added',
  LIST_CERTIFICATE_FAILURE         : 'Certificate List Failure',
  CERTIFICATE_DETAIL_FAILURE       : 'Certificate Detail Failure',
  CERTIFICATE_DETAIL               : 'Certificate Detail Success',
  UPDATE_CERTIFICATE_FAILURE       : 'Certificate update failure.',
  UPDATE_CERTIFICATE               : 'Certificate updated successfully.',
  DELETE_CERTIFICATE_FAILURE       : 'Certificate delete failure',
  DELETE_CERTIFICATE               : 'Certificate deleted successfully.',
  NO_DEFAULT_TASK_TYPE             : 'No Default Task Type Found for Review Certificate',
  NO_LOCATION_ASSOCIATED_EMPLOYEE  : 'No Location found associated with this team member',
  NO_EMPLOYEE_ASSOCIATED_LOCATION  : 'No Team members Found associated with this locations',
  REVIEW_CRT_APPROVED              : 'Certificate approved successfully.',
  REVIEW_CRT_NEED_ACCESS           : 'Need to have Permission for reviewing certificate',
  REVIEW_CRT_FAILURE               : 'Review Certificate Failure',
  REVIEW_CRT_REJECT                : 'Certificate rejected successfully.',
  GET_USERS                        : 'list of all users',
  ADD_EMPLOYEE_INTERACTION_FAILURE : 'Interaction record failed',
  ADD_EMPLOYEE_INTERACTION_SUCCESS : 'Interaction recorded successfully',
  POINTS_ADJUST_ERROR              : 'Error in adjusting Points',
  POINTS_ADJUST                    : 'Points adjusted successfully.',
  NO_POINTS_ADDED                  : 'No Points Added',
  LIST_POINTS_FAILURE              : 'Points List Failure',
  NO_INTERACTION_POINTS_ADDED      : 'No interaction Points Added',
  LIST_INTERACTION_POINTS_FAILURE  : 'Interaction Points List Failure',
  ROLE_PERMISSION_REQUIRED         : 'Valid Role and Permission Required',
  PERMISSION_REQUIRED              : 'You do not have required permission to try this API.',
  ACCOUNT_INACTIVATE_LOGOUT        : 'You are no longer associated with OneTeam360 customer portal',
  EMPLOYEE_DEACTIVATE              : 'Team member deactivated successfully',
  EMPLOYEE_ACTIVATE                : 'Team member activated successfully',
  EXCEED_EMPLOYEE                  : 'You cannot add more team members as you have exceeded your license limit. Please update it to add more employees.',
  REINVITE_SUCCESS                 : 'Reinvite mail sent successfully',
  PERMISSION_DENIED_TEAM_MEMBER_ID : 'Permission denied to update team member Id',
  TEAM_MEMBER_ID_EXISTS            : 'This team member ID already exists. Please try with different ID.',
  UPDATE_FILTER                    : 'Filter record update successfully',
  UPDATE_FILTER_FAILED             : 'Filter record update failed',
  GET_FILTER                       : 'Get Filter Record successfully.',
  GET_FILTER_FAILED                : 'Get Filter Record failed.',
  ADD_CHECKIN_REQUEST_SUCCESS      : 'Check-in Requested Successfully',
  ADD_CHECKIN_REQUEST_FAILURE      : 'Check-in Request Failed',
  CHECKIN_REQUEST_EXISTS           : 'Check-in Request already exist',
  UPDATE_CHECKIN_REQUEST_SUCCESS   : 'Check-in Request updated successfully',
  UPDATE_CHECKIN_REQUEST_FAILURE   : 'Check-in Request update failed',
  REVIEW_CHECKIN_REQUEST_SUCCESS   : 'Check-in reviewed successfully.',
  REVIEW_CHECKIN_REQUEST_FAILURE   : 'Check-in review failed',
  CHECKIN_APPROVE_SUCCESS          : 'Check-in approved successfully',
  CHECKIN_REJECT_SUCCESS           : 'Check-in rejected successfully',
  CHECKOUT_SUCCESS                 : 'Checked-Out Successfully',
  NO_FEEDBACK_RECORD               : 'No Feedback Records',
  FEEDBACK_REPORT_FAILURE          : 'Feedback report failed',
  FEEDBACK_SUBMIT_SUCCESS          : 'Feedback Submitted Successfully',
  FEEDBACK_SUBMIT_FAILURE          : 'Feedback Submit Failed',
  FEEDBACK_SUBMIT_EXISTS           : 'This Feedback already exist',
  HEALTH_OK                        : 'Health check passed',
  EXPORT_REPORT_SUCCESS            : 'Report exported successfully',
  EXPORT_REPORT_FAILURE            : 'Report export failed',
  CERTIFICATE_TYPE_NOT_EXIST       : 'Certificate type is not active',
  INVALID_CERTIFICATE_FILE_TYPE    : 'Invalid file type, allowed file types: jpg, png, pdf',
  PROFILE_PIC_NOT_SELECTED         : 'Please select an image to upload',
  INVALID_PROFILE_PIC_TYPE         : 'Invalid file type, allowed file types: jpg, png, jpeg',
  PROFILE_PIC_UPLOAD_SUCCESS       : 'Profile picture uploaded successfully',
  PROFILE_PIC_UPLOAD_FAILURE       : 'Profile picture upload failed',
  PROFILE_PIC_DIMENSION_ERROR      : 'The maximum dimension of profile picture should be STR_WIDTH * STR_HEIGHT pixels'
};
