module.exports = {
  REGISTER_SUCCESS             : 'successfully register',
  REGISTER_FAILURE             : 'signup request failed',
  USER_NOT_FOUND               : 'user with this email doesn\'t exist',
  RESET_PASSWORD_TOKEN_VALID   : 'The password reset link is valid',
  RESET_PASSWORD_TOKEN_EXPIRE  : 'The password reset link has expired. Please attempt reset password again.',
  RESET_PASSWORD_ALREADY_USED  : 'You have already reset your password using this link. Please attempt reset password again if required.',
  CREATE_PASSWORD_TOKEN_EXPIRE : 'The onboarding link has expired. Please contact your administrator.',
  CREATE_PASSWORD_ALREADY_USED : 'You have already created your password using this link. Please attempt reset password again if required.',
  ACCOUNT_STATUS               : 'Access restricted. Please contact administrator',
  ACCOUNT_EXPIRED              : 'Access restricted. Please contact administrator',
  INCORRECT_CREDENTIALS        : 'Please enter valid email ID/password to login',
  LOGIN_SUCCESS                : 'successfully login',
  LOGIN_FAILURE                : 'login request failed',
  FORGOT_PASSWORD              : 'If the entered email exist in the system, you would receive an email with instructions to reset your password',
  FORGOT_PASSWORD_FAILURE      : 'forgot password failed',
  RESET_PASSWORD               : 'The password has been reset successfully. You can start using the system now.',
  RESET_PASSWORD_FAILURE       : 'reset password failed',
  CHANGE_PASSWORD              : 'Password changed successfully',
  CHANGE_PASSWORD_FAILURE      : 'change password failed',
  CREATE_PASSWORD              : 'User account activation completed successfully.',
  CREATE_PASSWORD_FAILURE      : 'User account activation failure.',
  DELETE_USER                  : 'user successfully deleted',
  GET_USERS                    : 'list of all users',
  SELECT_TENANT                : 'select tenant success',
  SERVER_ERROR                 : 'something went wrong',
  RECORD_EXIST                 : 'Record Already Exist',
  DATABASE_QUERY_ERROR         : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE  : 'Error in Connecting with Database',
  ADMIN_ACCESS_REQUIRED        : 'Valid access required',
  AUTH_TOKEN_MISSING           : 'authorization header is missing',
  INVALID_AUTH_TOKEN           : 'invalid authorization header',
  INVALID_TOKEN                : 'invalid token',
  GET_LIST_ERROR               : 'list of system errors',
  DATA_NOT_FOUND               : 'record not found',
  GET_RECORD                   : 'Record(s) fetched successfully',
  ACCOUNT_INACTIVATE_LOGOUT    : 'You are no longer associated with OneTeam360 customer portal',
  CHANGEPASSWORD_INCORRECT_PWD : 'Please enter correct password',
  EMPLOYEE_NOT_ACTIVE          : 'You cannot reset your password as you are no longer associated with organization. Please contact your administrator',
  REFRESH_TOKEN_SUCCESS        : 'Successfully Refreshed Token',
  TOKEN_VALID                  : 'Token Already Valid',
  HEALTH_OK                    : 'Health check passed'

};
