
module.exports = {
    NOTI_ENTITY_NOT_FOUND        : 'No Notification Template found',
    GET_RECORD                   : 'Record(s) fetched successfully',
    NOT_RECEIVED_NOTIFICATION    : 'You have not yet received any notifications',
    SERVER_ERROR                 : 'something went wrong',
    DELETE_SUCCESS               : 'Notification deleted successfully',
    READ_SUCCESS                 : 'Notification read successfully',
    UPDATE_SUCCESS               : 'Notification updated successfully',
    DATE_FAILURE                 : 'Announcement end date cannot be less than start date.',
    ADD_FAILURE                  : 'Announcement add failed',
    ADD_SUCCESS                  : 'Announcement created successfully.',
    SOMETHING_WENT_WRONG         : 'something went wrong',
    GET_DATA_FAILED              : 'Not able to fetch Record. Something went wrong',
    GET_ANNOUNCEMENT             : 'Announcement list fetched successfully',
    DATA_NOT_FOUND               : 'No data found',
    ANN_UPDATE_SUCCESS           : 'Announcement updated successfully',
    UPDATE_FAILURE               : 'Announcement update failure',
    SOMETHING_WENT_WRONG_UPDATE  : 'Something went wrong in updating announcements',
    DELETE_ANNOUNCMENT           : 'Announcement status updated.',
    DELETE_ANNOUNCMENT_FAIL      : 'Announcement status update failed.',
    ANNOUNCMENT_TYPE_NOT_FOUND   : 'Announcement record not found',
    HEALTH_OK                    : 'Health check passed',
    API_TOKEN_MISSING            : 'Please enter API key or token.',
    INVALID_API_TOKEN            : 'Please enter valid API Key or token.',
    PERMISSION_REQUIRED          : 'You do not have required permission to try this API.',
    ACTIVE_ANNOUNCMENT_SUCCESS   : 'Announcement activated successfully',
    INACTIVE_ANNOUNCMENT_SUCCESS : 'Announcement inactivated successfully',
    UPDATE_STATUS_FAIL           : 'Announcement status update failed',
  };
  