#tenant
INSERT INTO `cron_job` (`name`, `code`, `description`) VALUES ('Certificate About to Expire', 'CERTIFICATE_ABOUT_TO_EXPIRE', 'Cron Job for Certificate About to Expire');
INSERT INTO `cron_job` (`name`, `code`, `description`) VALUES ('Task Overdue', 'TASK_OVERDUE', 'Cron Job for Task Overdue');
INSERT INTO `cron_job` (`name`, `code`, `description`) VALUES ('Competition Completion', 'COMPETITION_COMPLETION', 'Cron Job for Competition Completion');


INSERT INTO `masterdb`.`account_configuration_detail` (`account_configuration_detail_id`, `account_configuration_id`, `name`, `code`, `value`, `default_value`, `description`, `is_encrypted`, `is_editable`, `sequence`, `status`, `created_by`, `created_date`) VALUES ('9', '5', 'Time for cron task overdue', 'cron_task_overDue', '00:00', '00:00', ' ', '0', '0', '0', 'Active', '7', '2021-07-29 00:00:00');
INSERT INTO `masterdb`.`account_configuration_detail` (`account_configuration_detail_id`, `account_configuration_id`, `name`, `code`, `value`, `default_value`, `description`, `is_encrypted`, `is_editable`, `sequence`, `status`, `created_by`, `created_date`) VALUES ('10', '5', 'Time for cron certificate Expire', 'cron_certificate_expire', '00:00', '00:00', ' ', '0', '0', '0', 'Active', '7', '2021-07-29 00:00:00');
INSERT INTO `masterdb`.`account_configuration_detail` (`account_configuration_detail_id`, `account_configuration_id`, `name`, `code`, `value`, `default_value`, `description`, `is_encrypted`, `is_editable`, `sequence`, `status`, `created_by`, `created_date`) VALUES ('11', '5', 'Time for cron Point Calculation', 'cron_points_calculation', '00:00', '00:00', ' ', '0', '0', '0', 'Active', '7', '2021-07-29 00:00:00');
INSERT INTO `masterdb`.`account_configuration_detail` (`account_configuration_detail_id`, `account_configuration_id`, `name`, `code`, `value`, `default_value`, `description`, `is_encrypted`, `is_editable`, `sequence`, `status`, `created_by`, `created_date`) VALUES ('12', '5', 'Time for cron Point Notification ', 'cron_points_notification', '00:00', '00:00', ' ', '0', '0', '0', 'Active', '7', '2021-07-29 00:00:00');
INSERT INTO `masterdb`.`account_configuration_detail` (`account_configuration_detail_id`, `account_configuration_id`, `name`, `code`, `value`, `default_value`, `description`, `is_encrypted`, `is_editable`, `sequence`, `status`, `created_by`, `created_date`) VALUES ('13', '5', 'Time for cron Certificate Completion', 'cron_competiton_completion', '00:00', '00:00', ' ', '0', '0', '0', 'Active', '7', '2021-07-29 00:00:00');
