
module.exports = {
  SERVER_ERROR                 : 'something went wrong',
  DATABASE_QUERY_ERROR         : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE  : 'Error in Connecting with Database',
  GET_RECORD                   : 'Record(s) fetched successfully',
  DATA_NOT_FOUND               : 'No matching record found',
  PARAMETER_MISSING            : 'Id parameter missing',
  INVALID_PARAMETER            : 'Invalid parameter',
  GET_FAILURE                  : 'record get failed',
  DELETE_CACHE                 : 'cache deleted',
  AUTH_TOKEN_MISSING           : 'authorization header is missing',
  INVALID_AUTH_TOKEN           : 'invalid authorization header',
  API_TOKEN_MISSING            : 'Please enter API key or token.',
  INVALID_API_TOKEN            : 'Please enter valid API Key or token.',
  PERMISSION_REQUIRED          : 'You do not have required permission to try this API.',
  INVALID_TOKEN                : 'invalid token',
  SOMETHING_WENT_WRONG         : 'something went wrong, Report not added',
  GET_DATA_FAILED              : 'Not able to fetch Record. Something went wrong',
  DELETE_FAIL                  : 'Delete failed',
  ADD_REPORT_SUCCESS           : 'Report published successfully',
  ADD_REPORT_FAILURE           : 'Report published failed',
  REPORT_ALREADY_EXIST         : 'The report already exists for this location. Please try with different name.',
  UPDATE_REPORT_SUCCESS        : 'Report updated successfully',
  UPDATE_REPORT_FAILURE        : 'Report updated failed',
  ACTIVE_REPORT                : 'Daily report activated successfully',
  INACTIVE_REPORT              : 'Daily report inactivated successfully',
  ADD_QUESTION_SUCCESS         : 'Question added successfully',
  ADD_QUESTION_FAILURE         : 'Question added failed',
  UPDATE_QUESTION_SUCCESS      : 'Question updated successfully',
  UPDATE_QUESTION_FAILURE      : 'Question updated failed',
  DELETE_QUESTION              : 'Question deleted successfully',
  SUBMIT_REPORT_SUCCESS        : 'Report submitted successfully.',
  SAVE_AS_DRAFT_REPORT_SUCCESS : 'Report Saved as Draft successfully.',
  SUBMIT_REPORT_FAILURE        : 'Report submitted failed.',
  ROLE_PERMISSION_REQUIRED     : 'Valid Role and Permission Required',
  ACCOUNT_INACTIVATE_LOGOUT    : 'You are no longer associated with OneTeam360 customer portal',
  INVALID_EMPLOYEE             : 'You no longer have access to your company\'s OneTeam360 workspace. Please contact your administrator if you believe this is a mistake',
  HEALTH_OK                    : 'Health check passed'
};
