module.exports = {
  USER_NOT_FOUND               : 'user with this email doesn\'t exist',
  INCORRECT_CREDENTIALS        : 'Please enter valid email ID/password to login',
  LOGIN_SUCCESS                : 'successfully login',
  LOGIN_FAILURE                : 'login request failed',
  USER_ALREADY_EXISTS          : 'This email ID already exists. Please try with different email ID.',
  REGISTER_SUCCESS             : 'User account created successfully. A welcome email will be sent on registered email address shortly.',
  REGISTER_ACCESS_SUCCESS      : 'User account created successfully.',
  REGISTER_FAILURE             : 'User registration request failed',
  SERVER_ERROR                 : 'something went wrong',
  GET_RECORD                   : 'Record(s) fetched successfully',
  GET_RECORD_FAILURE           : 'Not able to fetch Record. Something went wrong',
  ADD_SUCCESS                  : 'Record add successful',
  ADD_FAILURE                  : 'Record add failed',
  UPDATE_SUCCESS               : 'User profile updated successfully',
  UPDATE_FAILURE               : 'Record update failed',
  DELETE_RECORD                : 'User successfully deleted',
  DELETE_FAILURE               : 'User Delete Failure',
  GET_USERS                    : 'list of all users',
  DATA_NOT_FOUND               : 'No matching record found',
  USER_NOT_ACTIVE              : 'Access restricted. Your account is inactive',
  INCORRECT_CREDENTIALS_PWD    : 'Incorrect username or password',
  FORGOT_PASSWORD              : 'If the entered email exist in the system, you would receive an email with instructions to reset your password',
  FORGOT_PASSWORD_FAILURE      : 'forgot password failed',
  RESET_PASSWORD               : 'The password has been reset successfully. You can start using the system now.',
  RESET_PASSWORD_FAILURE       : 'reset password failed',
  CHANGE_PASSWORD              : 'Password changed successfully.',
  CHANGE_PASSWORD_FAILURE      : 'change password failed',
  CHANGEPASSWORD_INCORRECT_PWD : 'Please enter correct password',
  CREATE_PASSWORD              : 'User account activation completed successfully.',
  CREATE_PASSWORD_FAILURE      : 'User account activation failure.',
  RESET_PASSWORD_TOKEN_VALID   : 'The password reset link is valid',
  RESET_PASSWORD_TOKEN_EXPIRE  : 'The password reset link has expired. Please attempt reset password again.',
  RESET_PASSWORD_ALREADY_USED  : 'You have already reset your password using this link. Please attempt reset password again if required.',
  CREATE_PASSWORD_TOKEN_EXPIRE : 'The onboarding link has expired. Please contact your administrator.',
  CREATE_PASSWORD_ALREADY_USED : 'You have already created your password using this link. Please attempt reset password again if required.',
  RECORD_EXIST                 : 'Record Already Exist',
  DATABASE_QUERY_ERROR         : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE  : 'Error in Connecting with Database',
  ADMIN_ACCESS_REQUIRED        : 'Valid access required',
  AUTH_TOKEN_MISSING           : 'authorization header is missing',
  INVALID_AUTH_TOKEN           : 'invalid authorization header',
  INVALID_TOKEN                : 'invalid token',
  GET_LIST_ERROR               : 'list of system errors',
  USER_ACTIVATE_SUCEESS        : 'User activated successfully',
  USER_INACTIVATE_SUCEESS      : 'User inactivated successfully',
  USER_ACTIVATE_FAIL           : 'User inactivation failed',
  USER_INACTIVATE_LOGOUT       : 'You are no longer associated with OneTeam360 admin portal.',
  WELCOME_USER                 : 'Welcome User',
  USER_NOT_EXISTS              : 'User does not exis',
  CUSTOMER_NOT_EXISTS          : 'Customer does not exist',
  SUCCESSFULL_TOKEN            : 'Token generated successfully',
  HEALTH_OK                    : 'Health check passed',
  REINVITE_SUCCESS             : 'Reinvite mail sent successfully',
};
