
module.exports = {
  SERVER_ERROR                     : 'something went wrong',
  DATABASE_QUERY_ERROR             : 'Error in Databse query usage',
  DATABASE_CONNECTION_FAILURE      : 'Error in Connecting with Database',
  GET_RECORD                       : 'Record(s) fetched successfully',
  DATA_NOT_FOUND                   : 'No matching record found',
  PARAMETER_MISSING                : 'Id parameter missing',
  INVALID_PARAMETER                : 'Invalid parameter',
  GET_FAILURE                      : 'record get failed',
  DELETE_CACHE                     : 'cache deleted',
  ADD_SUCCESS                      : 'Multi skill assessment saved successfully',
  ADD_FAILURE                      : 'Multi skill assessment save failed',
  UPDATE_SUCCESS                   : 'Multi skill assessment updated successfully',
  UPDATE_FAILURE                   : 'Multi skill assessment update failed',
  AUTH_TOKEN_MISSING               : 'authorization header is missing',
  INVALID_AUTH_TOKEN               : 'invalid authorization header',
  API_TOKEN_MISSING                : 'Please enter API key or token.',
  INVALID_API_TOKEN                : 'Please enter valid API Key or token.',
  PERMISSION_REQUIRED              : 'You do not have required permission to try this API.',
  INVALID_TOKEN                    : 'invalid token',
  SOMETHING_WENT_WRONG             : 'something went wrong, multi skill assessment not added',
  GET_DATA_FAILED                  : 'Not able to fetch Record. Something went wrong',
  ADD_TRAINING_EMPLOYEE_SUCCESS    : 'Assessment completed successfully',
  ADD_TRAINING_EMPLOYEE_FAILURE    : 'Assessment complete failed',
  DELETE_TRAINING_EMPLOYEE_SUCCESS : 'Assessment deleted successfully',
  DELETE_TRAINING_EMPLOYEE_FAILED  : 'Assessment delete failed',
  RETEST_TRAINING_EMPLOYEE_FAILURE : 'Assessment conducted failed',
  RETEST_TRAINING_EMPLOYEE_SUCCESS : 'Assessment retested successfully',
  ADD_GROUP_ACTIVITY               : 'Multi Skill Assessment submitted successfully',
  ADD_GROUP_ACTIVITY_FAILURE       : 'Multi skill assessment create failed',
  DELETE_GROUP_ACTIVITY            : 'Multi skill assessment deleted successfully',
  DELETE_FAIL                      : 'Delete failed',
  ROLE_PERMISSION_REQUIRED         : 'Valid Role and Permission Required',
  INVALID_EMPLOYEE                 : 'You no longer have access to your company\'s OneTeam360 workspace. Please contact your administrator if you believe this is a mistake',
  ADD_QUESTION_SUCCESS             : 'Question added successfully',
  ADD_QUESTION_FAILURE             : 'Question add failed',
  SKILL_QUESTION_ALREADY_EXISTS    : 'This question already exists. Please try with different name.',
  UPDATE_QUESTION_SUCCESS          : 'Quiz updated successfully',
  UPDATE_QUESTION_FAILURE          : 'Quiz update failed',
  DELETE_QUESTION                  : 'Question deleted successfully',
  SUBMIT_QUIZ_SUCCESS              : 'Question submitted successfully',
  SUBMIT_QUIZ_FAILURE              : 'Question submission failed',
  HEALTH_OK                        : 'Health check passed',
  EXPORT_REPORT_SUCCESS            : 'Report exported successfully',
  EXPORT_REPORT_FAILURE            : 'Report export failed',
};
